### ISSUE TITLE
[BUG] Using double quotes on a quest objective makes the text after it dissapear

### ISSUE THREAD

**Issue by JJBocanegra** [Forien/foundryvtt-forien-quest-log#38] opened 2020-06-23 13:22 UTC
**Describe the bug**
If I create an objective for a quest with the name `Foo "Bar"` and then edit it again, it will change it to just `Foo`

**To Reproduce**
1. Create a quest
2. Add a task with the name `Foo "Bar"`
3. Edit the task
4. The text `"Bar"` dissapeared

**Expected behavior**
It should keep the text

**Foundry Version:** v0.6.3

**System:** D&D 5th

**Comment by Forien** [comment] 2020-06-23 14:01
duplicate of #30 closed with v0.3.3.

Please update the Module :)

**Closed by Forien** 2020-06-23 14:01 UTC
Labels: bug
